const images = {
    // LOGO on Banner
    logo: require( "../../images/logo.png").default,
    // AUGrid section
    g1: require( "../../images/grid1.jpg").default,
    g2: require( "../../images/grid2.jpg").default,
    g3: require( "../../images/grid3.jpg").default,
    g4: require( "../../images/grid4.jpg").default,
    g5: require( "../../images/grid5.jpg").default,  
    g6: require( "../../images/grid6.jpg").default,  
    g7: require( "../../images/grid7.jpg").default,  
    g8: require( "../../images/grid8.jpg").default,  
    g9: require( "../../images/grid9.jpg").default, 
    g10: require( "../../images/grid10.jpg").default,  
    g11: require( "../../images/grid11.jpg").default,  
    g12: require( "../../images/grid12.jpg").default,       
    // Staff section
    nezu: require("../../images/nezu.jpg").default,
    rgirl: require( "../../images/r-girl.jpg").default,
    lrush: require( "../../images/lunch-rush.jpg").default,
    thirteen: require( "../../images/thirteen.jpg").default,
    hdog: require( "../../images/hound-dog.jpg").default,
    allmight: require( "../../images/allmight.jpg").default,
    eraserhead: require( "../../images/eraserhead.jpg").default,
    presentMic: require( "../../images/presentMic.jpg").default,
    cementoss: require( "../../images/cementoss.jpg").default,
    midnight: require( "../../images/midnight.jpg").default,
    sniper: require( "../../images/sniper.jpg").default,
    ectoplasm: require( "../../images/ectoplasm.jpg").default,
    vladking: require( "../../images/vladking.jpg").default,
    grantorino: require( "../../images/grantorino.jpg").default,
    // Class 1-A section
    ya: require("../../images/Yuuga_Aoyama.png").default,
    ma: require("../../images/Mina_Ashido.png").default,
    ta: require("../../images/Tsuyu_Asui.png").default,
    ti: require("../../images/Tenya_Iida.png").default,
    ou: require("../../images/Ochaco_Uraraka.png").default,
    mo: require("../../images/Mashirao_Ojiro.png").default,
    dk: require("../../images/Denki_Kaminari.png").default,
    ek: require("../../images/Eijirou_Kirishima.png").default,
    kk: require("../../images/Kouji_Kouda.png").default,
    rs: require("../../images/Rikido_Sato.png").default,
    ms: require("../../images/Mezo_Shoji.png").default,
    kj: require("../../images/Kyouka_Jirou.png").default,
    hs: require("../../images/Hanta_Sero.png").default,
    ft: require("../../images/Fumikage_Tokoyami.png").default,
    st: require("../../images/Shoto_Todoroki.png").default,
    th: require("../../images/Tooru_Hagakure.png").default,
    kb: require("../../images/Katsuki_Bakugo.png").default,
    im: require("../../images/Izuku_Midoriya.png").default,
    mm: require("../../images/Minoru_Mineta.png").default,
    my: require("../../images/Momo_Yaoyorozu.png").default,
    // Class 1-B section
    yaB: require("../../images/Yosetsu_Awase.png").default,
    sk: require("../../images/Sen_Kaibara.png").default,
    tk: require("../../images/Togaru_Kamakiri.png").default,
    sk2: require("../../images/Shihai_Kuroiro.png").default,
    ik: require("../../images/Itsuka_Kendo.png").default,
    yk: require("../../images/Yui_Kodai.png").default,
    kkB: require("../../images/Kinoko_Komori.png").default,
    is: require("../../images/Ibara_Shiozaki.png").default,
    js: require("../../images/Jurota_Shishida.png").default,
    ns: require("../../images/Nirengeki_Shoda.png").default,
    pt: require("../../images/Pony_Tsunotori.png").default,
    kt: require("../../images/Kosei_Tsuburaba.png").default,
    tt: require("../../images/Tetsutetsu_Tetsutetsu.png").default,
    stB: require("../../images/Setsuna_Tokage.png").default,
    mf: require("../../images/Manga_Fukidashi.png").default,
    jh: require("../../images/Juzo_Honenuki.png").default,
    kbB: require("../../images/Kojiro_Bondo.png").default,
    nm: require("../../images/Neito_Monoma.png").default,
    ry: require("../../images/Reiko_Yanagi.png").default,
    hr: require("../../images/Hiryu_Rin.png").default,
    // UA High School section
    hs1: require("../../images/hs-1.jpg").default,
    hs2: require("../../images/hs-2.jpg").default,
}

export default images;