const images = {
    // LOGO on Banner
    logo: require( "../../images/logo.png").default,
    // Season 1
    s1e1: require("../../images/S1EP1.jpg").default,
    s1e2: require("../../images/S1EP2.jpg").default,
    s1e3: require("../../images/S1EP3.jpg").default,
    s1e4: require("../../images/S1EP4.jpg").default,
    s1e5: require("../../images/S1EP5.jpg").default,
    s1e6: require("../../images/S1EP6.jpg").default,
    s1e7: require("../../images/S1EP7.jpg").default,
    s1e8: require("../../images/S1EP8.jpg").default,
    s1e9: require("../../images/S1EP9.jpg").default,
    s1e10: require("../../images/S1EP10.jpg").default,
    s1e11: require("../../images/S1EP11.jpg").default,
    s1e12: require("../../images/S1EP12.jpg").default,
    s1e13: require("../../images/S1EP13.jpg").default,
    s1e14: require("../../images/S1EP14.jpg").default,
    s1e15: require("../../images/S1EP15.jpg").default,
    // Season 2
    s2e1: require("../../images/S2EP1.jpg").default,
    s2e2: require("../../images/S2EP2.jpg").default,
    s2e3: require("../../images/S2EP3.jpg").default,
    s2e4: require("../../images/S2EP4.jpg").default,
    s2e5: require("../../images/S2EP5.jpg").default,
    s2e6: require("../../images/S2EP6.jpg").default,
    s2e7: require("../../images/S2EP7.jpg").default,
    s2e8: require("../../images/S2EP8.jpg").default,
    s2e9: require("../../images/S2EP9.jpg").default,
    s2e10: require("../../images/S2EP10.jpg").default,
    s2e11: require("../../images/S2EP11.jpg").default,
    s2e12: require("../../images/S2EP12.jpg").default,
    s2e13: require("../../images/S2EP13.jpg").default,
    s2e14: require("../../images/S2EP14.jpg").default,
    s2e15: require("../../images/S2EP15.jpg").default,
    s2e16: require("../../images/S2EP16.jpg").default,
    s2e17: require("../../images/S2EP17.jpg").default,
    s2e18: require("../../images/S2EP18.jpg").default,
    s2e19: require("../../images/S2EP19.jpg").default,
    s2e20: require("../../images/S2EP20.jpg").default,
    s2e21: require("../../images/S2EP21.jpg").default,
    s2e22: require("../../images/S2EP22.jpg").default,
    s2e23: require("../../images/S2EP23.jpg").default,
    s2e24: require("../../images/S2EP24.jpg").default,
    s2e25: require("../../images/S2EP25.jpg").default,
    // Season 3
    s3e1: require("../../images/S3EP1.jpg").default,
    s3e2: require("../../images/S3EP2.png").default,
    s3e3: require("../../images/S3EP3.jpg").default,
    s3e4: require("../../images/S3EP4.jpg").default,
    s3e5: require("../../images/S3EP5.png").default,
    s3e6: require("../../images/S3EP6.png").default,
    s3e7: require("../../images/S3EP7.jpg").default,
    s3e8: require("../../images/S3EP8.jpg").default,
    s3e9: require("../../images/S3EP9.jpg").default,
    s3e10: require("../../images/S3EP10.png").default,
    s3e11: require("../../images/S3EP11.png").default,
    s3e12: require("../../images/S3EP12.jpg").default,
    s3e13: require("../../images/S3EP13.jpg").default,
    s3e14: require("../../images/S3EP14.jpg").default,
    s3e15: require("../../images/S3EP15.jpg").default,
    s3e16: require("../../images/S3EP16.png").default,
    s3e17: require("../../images/S3EP17.png").default,
    s3e18: require("../../images/S3EP18.png").default,
    s3e19: require("../../images/S3EP19.png").default,
    s3e20: require("../../images/S3EP20.png").default,
    s3e21: require("../../images/S3EP21.jpg").default,
    s3e22: require("../../images/S3EP22.png").default,
    s3e23: require("../../images/S3EP23.png").default,
    s3e24: require("../../images/S3EP24.jpg").default,
    s3e25: require("../../images/S3EP25.jpg").default,
}

export default images;